typography_spectrum: 0.2009136780391051
color:
  brandStrength: 0.07487846384368985
  lightness: 0.7563907679396285
  saturation: 0.663500971216985
  rhythmicContrast: 0.4790591825733865
  brandColors:
    - '#F4F2ED'
    - '#FBF9F1'
    - '#FDFDF9'
    - '#F0ECE8'
    - '#FFFFFF'
github: true
layout_spectrum: 0.43641128236178933
analytics:
  google: UA-100562095-1
author:
  name: adec
  email: adrian@bbiab.com
  url: 'https://www.bbiab.com'
name: '{d-zign}'
url: 'https://d-zign.us/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: cool stuff!
    url: 'https://cool.d-zign.us'
    type: external
title: '{d-zign}'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9bc36689-82c5-42a0-a0c6-84f1b0cf6610.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9bc36689-82c5-42a0-a0c6-84f1b0cf6610.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: d-zign'rs & d-zigns from the gridoverse
purpose:
  - type: external
    url: 'https://contact.d-zign.us'
    label: talk 2 us!
